version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      PIHOLE_DNS_: 10.53.0.3#53
      TZ: America/Los_Angeles
    networks:
      pihole:
        ipv4_address: 10.53.0.2
    restart: unless-stopped
    # Volumes store your data between container upgrades
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d

  cloudflared:
    build:
      context: .
      dockerfile: Dockerfile.cloudflared
    environment:
      PRIMARY_DNS: https://1.1.1.1/dns-query
      SECONDARY_DNS: https://1.0.0.1/dns-query
    expose:
      - 53/tcp
      - 53/udp
    networks:
      pihole:
        ipv4_address: 10.53.0.3
    restart: unless-stopped
    volumes:
      - ./etc-cloudflared:/etc/cloudflared

networks:
  pihole:
    driver: bridge
    ipam:
      config:
        - subnet: 10.53.0.0/16
          gateway: 10.53.0.1
